package com.haseltonmediagroup.realdice3d

import android.content.Context
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.os.Bundle
import android.os.VibrationEffect
import android.os.Vibrator
import android.view.MotionEvent
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import com.haseltonmediagroup.realdice3d.databinding.ActivityMainBinding
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.sqrt

class MainActivity : AppCompatActivity(), SensorEventListener {
    private lateinit var binding: ActivityMainBinding
    private lateinit var sensorManager: SensorManager
    private lateinit var soundEngine: DiceSoundEngine
    private lateinit var advertisingPrivacy: AdvertisingPrivacy
    private var accelerometer: Sensor? = null
    private var lastRoll = 0L
    private var lastHaptic = 0L
    private var touchY = 0f
    private var diceCount = 2

    private val prefs by lazy { getSharedPreferences("realdice_prefs", Context.MODE_PRIVATE) }

    private val legalText = """
REALDICE 3D TERMS OF USE

RealDice 3D is provided by Haselton Media Group LLC as an entertainment and utility application for simulating dice rolls.

RANDOMNESS AND FAIRNESS
RealDice 3D is designed to produce random dice outcomes without predictive manipulation. Roll results are not intentionally altered, predetermined, favored, or influenced by advertising activity, previous rolls, user behavior, purchases, or any desired result. The application does not predict future events.

USE AT YOUR OWN RISK
You are solely responsible for how you use results generated by the app. RealDice 3D is not intended to provide gambling, financial, legal, medical, or other professional advice, and no result should be treated as a guarantee of any real-world outcome.

LIMITATION OF LIABILITY
To the maximum extent permitted by applicable law, Haselton Media Group LLC and its owners, officers, employees, contractors, affiliates, and licensors will not be liable for any direct, indirect, incidental, consequential, special, exemplary, or other damages, losses, claims, disputes, wagers, decisions, or actions arising from or related to use of the app or reliance on any roll result.

INDEMNIFICATION
To the maximum extent permitted by law, you agree to defend, indemnify, and hold harmless Haselton Media Group LLC and its affiliates from claims, liabilities, damages, losses, costs, and expenses arising from your misuse of the app, violation of these terms, or reliance on app-generated results.

NO WARRANTY
The app is provided “as is” and “as available” without warranties of any kind, express or implied, except where such warranties cannot legally be excluded.

By tapping ACCEPT, you acknowledge that you have read and agree to these Terms of Use.
    """.trimIndent()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        ViewCompat.setOnApplyWindowInsetsListener(binding.root) { view, insets ->
            val bars = insets.getInsets(WindowInsetsCompat.Type.systemBars() or WindowInsetsCompat.Type.displayCutout())
            view.setPadding(max(view.paddingLeft, bars.left), max(view.paddingTop, bars.top), max(view.paddingRight, bars.right), max(view.paddingBottom, bars.bottom))
            insets
        }
        ViewCompat.requestApplyInsets(binding.root)

        advertisingPrivacy = AdvertisingPrivacy(this, binding.adView)

        soundEngine = DiceSoundEngine(this)
        sensorManager = getSystemService(SENSOR_SERVICE) as SensorManager
        accelerometer = sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER)

        diceCount = prefs.getInt("dice_count", 2).coerceIn(1, 6)
        updateDiceCountUi()
        binding.dice3d.setDiceCount(diceCount)

        binding.diceMinusButton.setOnClickListener {
            if (diceCount > 1) {
                diceCount--
                prefs.edit().putInt("dice_count", diceCount).apply()
                updateDiceCountUi()
                binding.dice3d.setDiceCount(diceCount)
                binding.resultText.text = "ROLL: —"
            }
        }

        binding.dicePlusButton.setOnClickListener {
            if (diceCount < 6) {
                diceCount++
                prefs.edit().putInt("dice_count", diceCount).apply()
                updateDiceCountUi()
                binding.dice3d.setDiceCount(diceCount)
                binding.resultText.text = "ROLL: —"
            }
        }

        binding.dice3d.setOnImpactListener { strength ->
            soundEngine.playImpact(strength)
            if (strength >= 0.42f && System.currentTimeMillis() - lastHaptic > 85L) {
                lastHaptic = System.currentTimeMillis()
                val vibrator = getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
                val amplitude = (55 + strength * 95).toInt().coerceIn(45, 180)
                vibrator.vibrate(VibrationEffect.createOneShot(18, amplitude))
            }
        }

        binding.dice3d.setOnRollSettledListener { values ->
            val sum = values.sum()
            binding.resultText.text = if (values.size == 1) {
                "ROLL: ${values.first()}"
            } else {
                values.joinToString(" + ") + " = $sum"
            }
            saveRoll(values)
        }

        binding.historyButton.setOnClickListener { showHistory() }
        binding.legalButton.setOnClickListener { showLegal(false) }

        binding.diceArena.setOnClickListener { rollDice(1.0f) }
        binding.diceArena.setOnTouchListener { _, event ->
            when (event.actionMasked) {
                MotionEvent.ACTION_DOWN -> { touchY = event.y; true }
                MotionEvent.ACTION_UP -> {
                    val flick = touchY - event.y
                    if (abs(flick) > 90f) rollDice((abs(flick) / 420f).coerceIn(0.85f, 2.4f))
                    else rollDice(0.85f)
                    true
                }
                else -> true
            }
        }

        if (!prefs.getBoolean("terms_accepted", false)) showLegal(true)
        else advertisingPrivacy.start()
    }

    private fun updateDiceCountUi() {
        binding.diceCountText.text = if (diceCount == 1) "1 DIE" else "$diceCount DICE"
        binding.diceMinusButton.isEnabled = diceCount > 1
        binding.dicePlusButton.isEnabled = diceCount < 6
    }

    private fun saveRoll(values: List<Int>) {
        val time = SimpleDateFormat("MMM d, h:mm:ss a", Locale.getDefault()).format(Date())
        val result = if (values.size == 1) values.first().toString() else values.joinToString(" + ") + " = ${values.sum()}"
        val entry = "$time — ${values.size} ${if (values.size == 1) "die" else "dice"} — $result"
        val existing = prefs.getString("roll_history", "").orEmpty().lines().filter { it.isNotBlank() }
        val updated = (listOf(entry) + existing).take(100).joinToString("\n")
        prefs.edit().putString("roll_history", updated).apply()
    }

    private fun showHistory() {
        val history = prefs.getString("roll_history", "").orEmpty()
        val container = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val p = (20 * resources.displayMetrics.density).toInt()
            setPadding(p, p / 2, p, 0)
        }
        val historyText = TextView(this).apply {
            text = if (history.isBlank()) "No rolls logged yet." else history
            textSize = 15f
            setTextColor(0xFFFFFFFF.toInt())
            setTextIsSelectable(true)
        }
        val scroll = ScrollView(this).apply {
            addView(historyText)
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, (360 * resources.displayMetrics.density).toInt())
        }
        container.addView(scroll)

        val dialog = AlertDialog.Builder(this)
            .setTitle("Roll History")
            .setView(container)
            .setNegativeButton("CLOSE", null)
            .setPositiveButton("CLEAR HISTORY", null)
            .create()

        dialog.setOnShowListener {
            dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener {
                AlertDialog.Builder(this)
                    .setTitle("Clear roll history?")
                    .setMessage("This permanently removes the locally stored roll log on this device.")
                    .setPositiveButton("CLEAR") { _, _ ->
                        prefs.edit().remove("roll_history").apply()
                        historyText.text = "No rolls logged yet."
                    }
                    .setNegativeButton("CANCEL", null)
                    .show()
            }
        }
        dialog.show()
    }

    private fun showLegal(firstLaunch: Boolean) {
        val builder = AlertDialog.Builder(this)
            .setTitle(if (firstLaunch) "Terms of Use" else "Legal & Fairness")
            .setMessage(legalText)

        if (firstLaunch) {
            builder.setCancelable(false)
                .setPositiveButton("ACCEPT") { _, _ ->
                    prefs.edit().putBoolean("terms_accepted", true).apply()
                    advertisingPrivacy.start()
                }
                .setNegativeButton("DECLINE") { _, _ -> finish() }
        } else {
            builder.setPositiveButton("Close", null)
                .setNeutralButton("PRIVACY") { _, _ -> showPrivacy() }
        }
        builder.show()
    }

    private fun showPrivacy() {
        val choices = mutableListOf("Privacy policy", "Change advertising age group")
        if (advertisingPrivacy.optionsRequired) choices.add("Advertising privacy choices")
        AlertDialog.Builder(this)
            .setTitle("Privacy")
            .setItems(choices.toTypedArray()) { _, which ->
                when (which) {
                    0 -> AlertDialog.Builder(this)
                        .setTitle("RealDice 3D Privacy Policy")
                        .setMessage(resources.openRawResource(R.raw.privacy_policy).bufferedReader().use { it.readText() })
                        .setPositiveButton("CLOSE", null).show()
                    1 -> advertisingPrivacy.changeAgeGroup()
                    2 -> advertisingPrivacy.showOptions()
                }
            }
            .setNegativeButton("CLOSE", null)
            .show()
    }

    override fun onResume() {
        super.onResume()
        binding.dice3d.onResume()
        binding.adView.resume()
        accelerometer?.let { sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_GAME) }
    }

    override fun onPause() {
        sensorManager.unregisterListener(this)
        binding.dice3d.onPause()
        binding.adView.pause()
        super.onPause()
    }

    override fun onSensorChanged(event: SensorEvent) {
        val x = event.values[0]
        val y = event.values[1]
        val z = event.values[2]
        val g = sqrt(x * x + y * y + z * z) / SensorManager.GRAVITY_EARTH
        if (g > 2.35f && System.currentTimeMillis() - lastRoll > 800L) rollDice(g.coerceAtMost(3.2f))
    }

    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) = Unit

    private fun rollDice(force: Float) {
        lastRoll = System.currentTimeMillis()
        binding.resultText.text = "ROLLING…"
        soundEngine.playLaunch(force)
        binding.dice3d.roll(force)
    }

    override fun onDestroy() {
        advertisingPrivacy.destroy()
        soundEngine.release()
        super.onDestroy()
    }
}
