plugins { id 'com.android.application' }

android {
    namespace 'com.haselton.realcoin3d'
    compileSdk 37

    defaultConfig {
        applicationId 'com.haselton.realcoin3d'
        minSdk 23
        targetSdk 37
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
}
